# -*- coding: utf-8 -*-
"""project.m

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DsShpWi69zh4lywW7F4jKsI4hrwSKUWc
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

from sklearn.datasets import fetch_california_housing

house_df=fetch_california_housing()

type(house_df)

house_df.keys()

#check the description
print(house_df.DESCR)

print(house_df.data)

print(house_df.target)

print(house_df.feature_names)

dataset=pd.DataFrame(house_df.data, columns=house_df.feature_names)
dataset.head()

dataset['price']=house_df.target

dataset.head()

dataset.info()

#the stats
dataset.describe()

# check missing value
dataset.isnull().sum()

#Exploratory data analysis(EDA)
#correlation
dataset.corr()

import seaborn as sns
sns.pairplot(dataset)

plt.scatter(dataset['MedInc'],dataset['price'])
plt.xlabel('block group')
plt.ylabel('price')

plt.scatter(dataset['Latitude'],dataset['price'])
plt.xlabel('latitude')
plt.ylabel('price')

import seaborn as sns
sns.regplot(x='MedInc', y='price', data=dataset)

sns.regplot(x='Population', y='price', data=dataset)

#independent and dependent feature
X=dataset.drop('price',axis=1)
y=dataset['price']

X.head()

y.head()

#Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

X_train

X_test

#standardize the dataset
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)

X_test=scaler.transform(X_test)
import pickle 
pickle.dump(scaler,open('scaling.pkl','wb'))

X_train

X_test

from sklearn.linear_model import LinearRegression
model=LinearRegression()

model.fit(X_train,y_train)

#print the coefficient and intercept
print(model.coef_)

print(model.intercept_)

#prediction
pre=model.predict(X_test)

pre

#PLOT FOR THE PREDICTION
plt.scatter(y_test,pre)

#residuals error
res_error=y_test-pre
res_error

#plot the error
sns.displot(res_error,kind='kde')

#Scatter plot with respect to prediction and residuals error
plt.scatter(pre,res_error)

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_test,pre))
print(mean_squared_error(y_test,pre))
print(np.sqrt(mean_absolute_error(y_test,pre)))

# R sruare and adjusted R square
from sklearn.metrics import r2_score
score=r2_score(y_test,pre)
print(score)

1-(1-score)*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)

house_df.data[0].reshape(1,-1)

scaler.transform(house_df.data[0].reshape(1,-1))

model.predict(house_df.data[0].reshape(1,-1))

#Pickling The Model file for Deployment
import pickle

pickle.dump(model,open('regmodel.pkl','wb'))

pickel_model=pickle.load(open('regmodel.pkl','rb'))

pickel_model.predict(scaler.transform(house_df.data[0].reshape(1,-1)))